.. .. .. .. .. HIGHLIGHTING .. .. .. .. ..

.. MDL source code

.. highlight:: mdl
   :linenothreshold: 5

.. role:: inline-mdl(literal)

.. TYPE name

.. role:: t(literal)
   :class: typename

.. role:: ut(t)
   :class: underline typename

.. role:: param(emphasis)

.. default-role:: inline-mdl

.. .. .. .. .. SUBSTITUTIONS .. .. .. .. ..

.. |beginner-mark| replace:: [1]

.. |sic| replace:: *[sic]*

.. role:: expert

.. |ATOM| replace:: :t:`ATOM`
.. |F/SUBR| replace:: :t:`F`\ /\ :t:`SUBR`
.. |FIX| replace:: :t:`FIX`
.. |FLOAT| replace:: :t:`FLOAT`
.. |FORM| replace:: :t:`FORM`
.. |FSUBR| replace:: :t:`FSUBR`
.. |LIST| replace:: :t:`LIST`
.. |STRING| replace:: :t:`STRING`
.. |SUBR| replace:: :t:`SUBR`
.. |TYPE| replace:: :t:`TYPE`
.. |VECTOR| replace:: :t:`VECTOR`
