.. role:: expert

.. .. .. .. .. HIGHLIGHTING .. .. .. .. ..

.. highlight:: mdl
   :linenothreshold: 5

.. role:: inline-mdl(literal)
.. default-role:: inline-mdl

.. role:: param(emphasis)

.. role:: t(literal)
   :class: typename

.. role:: ut(t)
   :class: underline typename

.. .. .. .. .. SUBSTITUTIONS .. .. .. .. ..

.. |beginner-mark| replace:: [1]
.. |sic| replace:: *[sic]*


.. |ASOC| replace:: :t:`ASOC`
.. |ATOM| replace:: :t:`ATOM`
.. |BYTES| replace:: :t:`BYTES`
.. |CHANNEL| replace:: :t:`CHANNEL`
.. |DECL| replace:: :t:`DECL`
.. |FIX| replace:: :t:`FIX`
.. |FLOAT| replace:: :t:`FLOAT`
.. |FORM| replace:: :t:`FORM`
.. |FRAME| replace:: :t:`FRAME`
.. |FUNCTION| replace:: :t:`FUNCTION`
.. |FSUBR| replace:: :t:`FSUBR`
.. |LIST| replace:: :t:`LIST`
.. |LOCA| replace:: :t:`LOCA`
.. |LOCATIVE| replace:: :t:`LOCATIVE`
.. |LOCB| replace:: :t:`LOCB`
.. |LOCD| replace:: :t:`LOCD`
.. |LOCS| replace:: :t:`LOCS`
.. |NEWTYPE| replace:: :t:`NEWTYPE`
.. |OBLIST| replace:: :t:`OBLIST`
.. |PRIMTYPE| replace:: :t:`PRIMTYPE`
.. |PROCESS| replace:: :t:`PROCESS`
.. |RSUBR| replace:: :t:`RSUBR`
.. |STRING| replace:: :t:`STRING`
.. |SUBR| replace:: :t:`SUBR`
.. |TEMPLATE| replace:: :t:`TEMPLATE`
.. |TUPLE| replace:: :t:`TUPLE`
.. |TYPE| replace:: :t:`TYPE`
.. |TYPEPRIM| replace:: :t:`TYPEPRIM`
.. |UVECTOR| replace:: :t:`UVECTOR`
.. |VECTOR| replace:: :t:`VECTOR`

.. |F/SUBR| replace:: :t:`F`\ /\ :t:`SUBR`

.. .. |GVAL| replace:: :func:`GVAL`
.. |G/LVAL| replace:: :t:`G`\ /\ :t:`LVAL`
.. .. |LVAL| replace:: :func:`LVAL`
.. |RSUBR(-ENTRY)| replace:: :t:`RSUBR`\ (\ :t:`-ENTRY`\ )
.. .. |PNAME| replace:: :func:`PNAME`
.. |T| replace:: ``T``

.. |GVAL| replace:: :t:`GVAL`
.. |LVAL| replace:: :t:`LVAL`
.. |PNAME| replace:: :t:`PNAME`
